Espanol equ 0

If Espanol
  Texto_Menu    DM T_3,T_PUNTO,T_ESPACIO,"JUGAR",255
  Texto_Menu1   DM T_1,T_PUNTO,T_ESPACIO,"INTRO",255
  Texto_Menu2   DM T_2,T_PUNTO,T_ESPACIO,"M",T_U,"SICA"  ,255

  Texto_Menu11  DM T_1,T_PUNTO,T_ESPACIO,"TEMPLO",255
  Texto_Menu12  DM T_2,T_PUNTO,T_ESPACIO,"SELVA",255
  Texto_Menu13  DM T_3,T_PUNTO,T_ESPACIO,"HIELO",255
  Texto_Menu14  DM T_4,T_PUNTO,T_ESPACIO,"FUEGO",255

  Texto_NuevoMenu DM "LA",T_ESPACIO,"BENEVOLENCIA",T_ESPACIO,"DE",T_ESPACIO,T_MR,"A",T_COMA,T_ESPACIO,T_MP,"HANTIS",T_ESPACIO,"Y",T_ESPACIO,T_MA,"M",T_O,"N"
                  DM T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,T_ESPACIO,"TE",T_ESPACIO,"PROPORCIONA"
                  DM T_ESPACIO,"PUNTOS",T_ESPACIO,"DE",T_ESPACIO,"CONTROL",T_PUNTO,"STOP",T_PUNTO,T_ESPACIO
                  DM "POR",T_ESPACIO,"SU",T_ESPACIO,"GRACIA",T_ESPACIO,"Y",T_ESPACIO,"A",T_ESPACIO,"SABIENDAS",T_ESPACIO,T_PUNTO,"STOP",T_PUNTO
                  DM T_ESPACIO,"DE",T_ESPACIO,"LO",T_ESPACIO,"IMPOSIBLE",T_ESPACIO,"DE",T_ESPACIO,"TU",T_ESPACIO,"MISI",T_O,"N",255

  Texto_End1  DM "ENHORABUENA",T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,T_ESPACIO,"DEL",T_ESPACIO,"TEMPLO",T_ESPACIO,"DE",T_ESPACIO,T_MA,"BU",T_ESPACIO,T_MS,"IMBEL"
              DM T_ESPACIO,"HAS",T_ESPACIO,"CONSEGUIDO",T_ESPACIO,"ESCAPAR",T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,T_ESPACIO,"Y",T_ESPACIO,"DE",T_ESPACIO,"LA"
              DM T_ESPACIO,"MALDICI",T_O,"N",T_ESPACIO,"TE",T_ESPACIO,"PODR",T_A,"S",T_ESPACIO,"POR",T_ESPACIO,"FIN",T_ESPACIO,"LIBERAR",T_ESPACIO,T_PUNTO
              DM "STOP",T_PUNTO,T_ESPACIO,"A",T_ESPACIO,"TU",T_ESPACIO,"ASPECTO",T_ESPACIO,"NORMAL",T_ESPACIO,"VOLVER",T_A,"S",T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,T_ESPACIO
              DM "Y",T_ESPACIO,"SINO",T_ESPACIO,"YA",T_ESPACIO,"LO",T_ESPACIO,"VER",T_A,"S",T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,255
  Texto_End2  DM "POR",T_ESPACIO,"FIN",T_ESPACIO,"MI",T_ESPACIO,"SUE",T_ENIE,"O",T_ESPACIO,"HECHO",T_ESPACIO
              DM "REALIDAD",T_EXCLAMACION,255
  Texto_End21 DM T_ESPACIO,T_ESPACIO,T_ESPACIO,T_ESPACIO,T_ESPACIO,T_ESPACIO,"NO",T_ESPACIO,"QUIERO",T_ESPACIO,"DESPERTAR",T_EXCLAMACION,T_ESPACIO,T_ESPACIO,T_ESPACIO,T_ESPACIO,T_ESPACIO,T_ESPACIO,255
  Texto_End5  DM "UY",T_ESPACIO,"PERD",T_O,"N",T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,T_ESPACIO,"TANTO",T_ESPACIO,"POLO",T_COMA,T_ESPACIO,"ICECLUB",T_ESPACIO,"O",T_ESPACIO,"CAMELOT"
              DM T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,T_ESPACIO,"QUE",T_ESPACIO,"EN",T_ESPACIO,"PHANTIS",T_ESPACIO,"TE",T_ESPACIO,"HE",T_ESPACIO,"CAMBIADO",T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,255
  Texto_End6  DM "BUENO",T_COMA,T_ESPACIO,"VA",T_PUNTO,T_PUNTO,T_PUNTO,"NO",T_ESPACIO,"EST",T_A,T_ESPACIO,"MAL",T_PUNTO,T_PUNTO,T_PUNTO,255

  Texto_End7  DM T_ESPACIO,T_ESPACIO,"PERD",T_O,"N",T_COMA,T_ESPACIO,"PARA",T_ESPACIO,"IR",T_ESPACIO,"A",T_ESPACIO,"CAMELOT",T_INTERROGACION,255

  Texto_Intro1  DM "ENHORABUENA",T_PUNTO,T_ESPACIO,"STOP",T_PUNTO,T_ESPACIO,"SE",T_ESPACIO
                DM "HA",T_ESPACIO,"ROTO",T_ESPACIO,"LA",T_ESPACIO,"MALDICI",T_O,"N",T_ESPACIO,"DE",T_ESPACIO
                DM T_MA,"BU",T_ESPACIO,T_MS,"IMBEL",T_PUNTO,T_ESPACIO,"STOP",T_PUNTO,T_ESPACIO,"NOS",T_ESPACIO,"VEREMOS",T_ESPACIO
                DM "EN",T_ESPACIO,"EL",T_ESPACIO,"POLO",T_PUNTO,T_ESPACIO,"STOP",T_PUNTO,255
  Texto_Intro2  DM "PREP",T_A,"RATE",T_ESPACIO,"PARA",T_ESPACIO,"EL",T_ESPACIO,"VIAJE",T_COMA,T_ESPACIO,"NO"
                DM T_ESPACIO,"SER",T_A,T_ESPACIO,"SENCILLO",T_PUNTO,T_ESPACIO,"STOP",T_PUNTO,255
  Texto_Intro3  DM T_4,"MHZ",T_PUNTO,"ES",T_GUION,"LORDFRED",255
                DM 255
                DM T_ESPACIO,T_ESPACIO,T_ESPACIO,"PRESENTAN",255
    
  Texto_Intro01 DM "TEMPLO",T_ESPACIO,"DE",T_ESPACIO,T_MR,"AMSES",T_ESPACIO,"II",255
  Texto_Intro5  DM "A",T_ESPACIO,"LOS",T_ESPACIO,"GR",T_A,"FICOS",255
                DM 255
                DM T_ESPACIO,T_ESPACIO,T_ESPACIO,"LORDFRED",255
  Texto_Intro6  DM "PROGRAMANDO",255
                DM 255
                DM T_ESPACIO,"JGNAVARRO",255
  Texto_Intro7  DM "A",T_ESPACIO,"LA",T_ESPACIO,"M",T_U,"SICA",255
                DM 255
                DM T_ESPACIO,T_ESPACIO,"MCKLAIN",255

  Texto_Outtro10  DM "JA",T_ESPACIO,"JA",T_ESPACIO,"JA",T_PUNTO,T_PUNTO,T_PUNTO,T_ESPACIO
  Texto_Outtro11  DM "HAS",T_ESPACIO,"SUCUMBIDO",T_ESPACIO,"AL",T_ESPACIO
  Texto_Outtro12  DM "PODER",T_ESPACIO,"DE",T_ESPACIO
  Texto_Outtro13  DM T_MA,"BU",T_ESPACIO,T_MS,"IMBEL",T_PUNTO,T_ESPACIO
  Texto_Outtro14  DM "ERES",T_ESPACIO,"MUY",T_ESPACIO,"MALO",T_ESPACIO
  Texto_Outtro15  DM T_PUNTO,"STOP",T_PUNTO,255

  Texto_Marcador  DM T_MA,T_ENIE,"O",T_ESPACIO,T_2,T_0,T_1,T_7,T_ESPACIO,T_GUION,T_ESPACIO,T_4,"MHZ",T_PUNTO,"ES",T_ESPACIO,"Y",T_ESPACIO,"LORDFRED",T_COMA,T_ESPACIO,"PRESENTAN",T_COMA,T_ESPACIO,T_MP,"ROFANATION",T_ESPACIO,T_2,T_ESPACIO
                  DM T_ME,"SCAPE",T_ESPACIO,"FROM",T_ESPACIO,T_MA,"BU",T_ESPACIO,T_MS,"IMBEL",255
else
  Texto_Menu    DM T_3,T_PUNTO,T_ESPACIO,"START",255
  Texto_Menu1   DM T_1,T_PUNTO,T_ESPACIO,"INTRO",255
  Texto_Menu2   DM T_2,T_PUNTO,T_ESPACIO,"MUSIC"  ,255

  Texto_Menu11  DM T_1,T_PUNTO,T_ESPACIO,"TEMPLE",255
  Texto_Menu12  DM T_2,T_PUNTO,T_ESPACIO,"JUNGLE",255
  Texto_Menu13  DM T_3,T_PUNTO,T_ESPACIO,"ICE",255
  Texto_Menu14  DM T_4,T_PUNTO,T_ESPACIO,"FIRE",255

  Texto_NuevoMenu DM "THE",T_ESPACIO,"BENEVOLENCE",T_ESPACIO,"OF",T_ESPACIO,T_MR,"A",T_COMA,T_ESPACIO,T_MP,"HANTIS",T_ESPACIO,"AND",T_ESPACIO,T_MA,"M",T_O,"N"
                  DM T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,T_ESPACIO,"GIVES",T_ESPACIO,"YOU"
                  DM T_ESPACIO,"CHECKPOINTS",T_ESPACIO,"STOP",T_PUNTO,T_ESPACIO
                  DM "BY",T_ESPACIO,"THEIR",T_ESPACIO,"GRACE",T_ESPACIO,"AND",T_ESPACIO,"FOR",T_ESPACIO,T_PUNTO,"STOP",T_PUNTO
                  DM T_ESPACIO,"YOUR",T_ESPACIO,"IMPOSSIBLE",T_ESPACIO,"MISSION",255

  Texto_End1  DM "CONGRATULATIONS",T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,T_ESPACIO,"FROM",T_ESPACIO,"THE",T_ESPACIO,T_MA,"BU",T_ESPACIO,T_MS,"IMBEL"
              DM T_ESPACIO,"TEMPLE",T_ESPACIO,"YOU",T_ESPACIO,"MANAGED",T_ESPACIO,"TO",T_ESPACIO,"ESCAPE",T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,T_ESPACIO,"AND",T_ESPACIO,"FROM",T_ESPACIO,"THE"
              DM T_ESPACIO,"CURSE",T_ESPACIO,"YOU",T_ESPACIO,"WILL",T_ESPACIO,"BE",T_ESPACIO,"FREE",T_ESPACIO,T_PUNTO
              DM "STOP",T_PUNTO,T_ESPACIO,"TO",T_ESPACIO,"YOUR",T_ESPACIO,"NORMAL",T_ESPACIO,"APPEARANCE",T_ESPACIO,"YOU",T_ESPACIO,"WILL",T_ESPACIO,"RETURN",T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,T_ESPACIO
              DM "YOU",T_ESPACIO,"WILL",T_ESPACIO,"SEE",T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,255
  Texto_End2  DM T_ESPACIO,T_ESPACIO,"FINALLY",T_ESPACIO,"MY",T_ESPACIO,"DREAM",T_ESPACIO,"CAME",T_ESPACIO,"TRUE",T_EXCLAMACION,255
  Texto_End21 DM T_ESPACIO,T_ESPACIO,T_ESPACIO,"I",T_ESPACIO,"DONT",T_ESPACIO,"WANT",T_ESPACIO,"TO",T_ESPACIO,"WAKE",T_ESPACIO,"UP",T_EXCLAMACION,T_ESPACIO,T_ESPACIO,T_ESPACIO,255
  Texto_End5  DM "UH",T_ESPACIO,"SORRY",T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,T_ESPACIO,"TOO",T_ESPACIO,"MUCH",T_ESPACIO,"POLE",T_COMA,T_ESPACIO,"ICECLUB",T_ESPACIO,"OR",T_ESPACIO,"CAMELOT"
              DM T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,T_ESPACIO,"IN",T_ESPACIO,"PHANTIS",T_ESPACIO,"I",T_ESPACIO,"CHANGED",T_ESPACIO,"YOU",T_ESPACIO,T_PUNTO,"STOP",T_PUNTO,255
  Texto_End6  DM T_ESPACIO,T_ESPACIO,T_ESPACIO,"WELL",T_COMA,T_ESPACIO,"OK",T_PUNTO,T_PUNTO,T_PUNTO,"NOT",T_ESPACIO,"BAD",T_PUNTO,T_PUNTO,T_PUNTO,255

  Texto_End7  DM "EXCUSE",T_ESPACIO,"ME",T_COMA,T_ESPACIO,"WICH",T_ESPACIO,"WAY",T_ESPACIO,"TO",T_ESPACIO,"CAMELOT",T_INTERROGACION,255

  Texto_Intro1  DM "CONGRATULATIONS",T_PUNTO,T_ESPACIO,"STOP",T_PUNTO,T_ESPACIO,"THE",T_ESPACIO
                DM "CURSE",T_ESPACIO,"OF",T_ESPACIO
                DM T_MA,"BU",T_ESPACIO,T_MS,"IMBEL",T_ESPACIO,"HAS",T_ESPACIO,"BEEN",T_ESPACIO,"BROKEN",T_PUNTO,T_ESPACIO,"STOP",T_PUNTO,T_ESPACIO,"SEE",T_ESPACIO,"YOU",T_ESPACIO
                DM "AT",T_ESPACIO,"THE",T_ESPACIO,"NORTH",T_ESPACIO,"POLE",T_PUNTO,T_ESPACIO,"STOP",T_PUNTO,255
  Texto_Intro2  DM "GET",T_ESPACIO,"READY",T_ESPACIO,"FOR",T_ESPACIO,"THE",T_ESPACIO,"TRIP",T_COMA,T_ESPACIO,"IT"
                DM T_ESPACIO,"WONT",T_ESPACIO,"BE",T_ESPACIO,"EASY",T_PUNTO,T_ESPACIO,"STOP",T_PUNTO,255
  Texto_Intro3  DM T_4,"MHZ",T_PUNTO,"ES",T_GUION,"LORDFRED",255
                DM 255
                DM T_ESPACIO,T_ESPACIO,T_ESPACIO,"PRESENT",255
    
  Texto_Intro01 DM "TEMPLE",T_ESPACIO,"OF",T_ESPACIO,T_MR,"AMSES",T_ESPACIO,"II",255
  Texto_Intro5  DM "GRAPHICS",T_ESPACIO,"BY",255
                DM 255
                DM "LORDFRED",255
  Texto_Intro6  DM "CODE",T_ESPACIO,"BY",255
                DM 255
                DM "JGNAVARRO",255
  Texto_Intro7  DM "MUSIC",T_ESPACIO,"BY",255
                DM 255
                DM "MCKLAIN",255

  Texto_Outtro10  DM "HA",T_ESPACIO,"HA",T_ESPACIO,"HA",T_PUNTO,T_PUNTO,T_PUNTO,T_ESPACIO
  Texto_Outtro11  DM "YOU",T_ESPACIO,"FELT",T_ESPACIO,"UNDER",T_ESPACIO,"THE",T_ESPACIO
  Texto_Outtro12  DM "POWER",T_ESPACIO,"OF",T_ESPACIO
  Texto_Outtro13  DM T_MA,"BU",T_ESPACIO,T_MS,"IMBEL",T_PUNTO,T_ESPACIO
  Texto_Outtro14  DM "YOU",T_ESPACIO,"SUCK",T_ESPACIO
  Texto_Outtro15  DM T_PUNTO,"STOP",T_PUNTO,255

  Texto_Marcador  DM "YEAR",T_ESPACIO,T_2,T_0,T_1,T_7,T_ESPACIO,T_GUION,T_ESPACIO,T_4,"MHZ",T_PUNTO,"ES",T_ESPACIO,"AND",T_ESPACIO,"LORDFRED",T_COMA,T_ESPACIO,"PRESENT",T_COMA,T_ESPACIO,T_MP,"ROFANATION",T_ESPACIO,T_2,T_ESPACIO
                  DM T_ME,"SCAPE",T_ESPACIO,"FROM",T_ESPACIO,T_MA,"BU",T_ESPACIO,T_MS,"IMBEL",255
endif
